#!/bin/bash
SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"


if [[ -f $SCRIPT_FILE ]]; then
	echo "File already exist"
else
	echo "#!/bin/bash" > $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
	echo "$1 file created"
	nvim $SCRIPT_FILE
fi
